jobs:
  builddeployjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Install docker
        uses: docker/setup-buildx-action@v3
      - name: Build the code
        run: mvn package
      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: Bhushan9144
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Dockerfile and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: sonal04/myimagejava
          push: true
